---
abstract: 'the FITesque framework!'
author:
  - 'Scott McWhirter <konobi@cpan.org>'
build_requires:
  Test::Exception: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: bsd
resources:
  license: http://www.opensource.org/licenses/bsd-license.php
  repository: http://github.com/konobi/Test-FITesque/tree/master
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-FITesque
no_index:
  directory:
    - inc
    - t
requires:
  Class::Data::Inheritable: 0
  Module::Load: 0
  Test::Builder: 0.64_01
version: 0.03
